.TH GITSUPERV 1 2014-08-12

.SH NAME
\fBgitsuperv\fP \- Watch your git repositories status

.SH SYNOPSIS

\fBgitsuperv\fP [\fB-d\fP=dir] [\fB-c\fP]

.SH DESCRIPTION
\fBgitsuperv\fP reports the status of your git repositories
from your work base directory

.SH OPTIONS
.TP
.BR \-d ", " \-\-dir =\fIDIR
The base directory where the software will be rooted
.TP
.BR \-c ", " \-\-colors
Use colors to display the results

.SH FILES
Optionally, you can create a \fI~/.gitsuperv\fP file, which is the main
config files with the following options:
.TP
dir=/path/your/work/directory
colors=1

.SH BUGS
Please report bugs at https://github.com/pierre-lecocq/gitsuperv/issues

.SH SEE ALSO
\fBgit\fP(1)

.SH AUTHOR
\fBgitsuperv\fP was written by Pierre Lecocq <pierre.lecocq@gmail.com>
