Language: c

compiler:
  - gcc

branches:
  only:
    - master

before_install:
  - sudo apt-get install cmake build-essential
  - git clone https://github.com/libgit2/libgit2
  - cd libgit2 && mkdir build && cd build
  - cmake .. && sudo cmake --build . --target install && cd ../..

script:
  - make
