.TH GITSUPERV 1 2014-08-12

.SH NAME
\fBgitsuperv\fP \- Watch your git repositories status

.SH DESCRIPTION
\fBgitsuperv\fP reports the status of your git repositories
from your work base directory

An option can be used to specify the base directory. This option
is configurable via a config file.

.SH SEE ALSO
\fBgit\fP(1)

.SH AUTHOR
\fBgitsuperv\fP was written by Pierre Lecocq <pierre.lecocq@gmail.com>.
